package edu.unindra.kkp_kelompok4.home;

import com.mysql.jdbc.Blob;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import edu.unindra.kkp_kelompok4.cashier.Cashier;
import edu.unindra.kkp_kelompok4.master.employeeForm;
import edu.unindra.kkp_kelompok4.master.itemForm;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;
/**
 *
 * @author fadli
 */
public class homeApp extends javax.swing.JFrame {

    /**
     * Creates new form HomeDesainApp
     */
    public homeApp(String idEmployee,String employeeName, String role, Blob picture) {
        initComponents();
        execute();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        timeLabel();
	labelRole.setText(role);
	labelName.setText(employeeName);
	labelIdEmployee.setText(idEmployee);
	
	
	    try {
		  byte[]profilePic = picture.getBytes( 1, (int) picture.length());
		  ImageIcon img = new ImageIcon(profilePic);
		  
		  //Ukuran Jlabel untuk gambar
		  int labelWidth=150;
		  int labelHeight=90;
		  
		  //ambil ukuran gambar asli
		  int pictureWidth= img.getIconWidth();
		  int pictureHeight= img.getIconHeight();
		  
		  //hitung skala gambar
		  double scaleX = (double) labelWidth/ (double) pictureWidth;
		  double scaleY = (double) labelHeight/(double) pictureHeight;
		  double scale = Math.min(scaleX, scaleY);
		  
		  //ubah ukuran gambar dengan skala
		  Image scaledPicture = img.getImage().getScaledInstance((int)(scale*pictureWidth),(int)(scale*pictureHeight),Image.SCALE_SMOOTH);
		  //set gambar
		  labelPicture.setIcon(new ImageIcon(scaledPicture));

		  
	    } catch (Exception e) {
	    }
	
	
        
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                panel_nav = new javax.swing.JPanel();
                labelMinimarket = new javax.swing.JLabel();
                labelIcon = new javax.swing.JLabel();
                labelTime = new javax.swing.JLabel();
                Separate = new javax.swing.JLabel();
                Seperate = new javax.swing.JLabel();
                labelDate = new javax.swing.JLabel();
                labelName = new javax.swing.JLabel();
                labelRole = new javax.swing.JLabel();
                labelIdEmployee = new javax.swing.JLabel();
                labelPicture = new javax.swing.JLabel();
                panel_side = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                menus = new javax.swing.JPanel();
                panel_content = new javax.swing.JPanel();
                panel_Utama = new javax.swing.JPanel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowOpened(java.awt.event.WindowEvent evt) {
                                formWindowOpened(evt);
                        }
                });

                panel_nav.setBackground(new java.awt.Color(0, 0, 255));
                panel_nav.setPreferredSize(new java.awt.Dimension(830, 70));
                panel_nav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                labelMinimarket.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
                labelMinimarket.setForeground(new java.awt.Color(255, 255, 255));
                labelMinimarket.setText("MINIMARKET XYZ");
                panel_nav.add(labelMinimarket, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 406, -1));

                labelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/HomeApp/Shopping.png"))); // NOI18N
                panel_nav.add(labelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, 92, -1));

                labelTime.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                labelTime.setForeground(new java.awt.Color(255, 255, 255));
                labelTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                labelTime.setText("00-00-0000 00:00:00");
                panel_nav.add(labelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 30, 185, 30));

                Separate.setFont(new java.awt.Font("Candara", 1, 12)); // NOI18N
                Separate.setForeground(new java.awt.Color(255, 255, 255));
                Separate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                Separate.setText("|");
                panel_nav.add(Separate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 10, 40));

                Seperate.setFont(new java.awt.Font("Century Gothic", 0, 48)); // NOI18N
                Seperate.setForeground(new java.awt.Color(255, 255, 255));
                Seperate.setText("|");
                panel_nav.add(Seperate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, -1, -1));

                labelDate.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                labelDate.setForeground(new java.awt.Color(255, 255, 255));
                labelDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                labelDate.setText("Tanggal dan waktu");
                panel_nav.add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 10, 122, -1));

                labelName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                labelName.setForeground(new java.awt.Color(255, 255, 255));
                labelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                labelName.setText("Nama Kasir");
                panel_nav.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 360, 30));

                labelRole.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                labelRole.setForeground(new java.awt.Color(255, 255, 255));
                labelRole.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                labelRole.setText("Role");
                panel_nav.add(labelRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, 60, -1));

                labelIdEmployee.setFont(new java.awt.Font("Century Gothic", 2, 12)); // NOI18N
                labelIdEmployee.setForeground(new java.awt.Color(255, 255, 255));
                labelIdEmployee.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                labelIdEmployee.setText("Id Employee");
                panel_nav.add(labelIdEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 10, 122, -1));
                panel_nav.add(labelPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 10, 60, 50));

                getContentPane().add(panel_nav, java.awt.BorderLayout.PAGE_START);

                panel_side.setBackground(new java.awt.Color(255, 255, 255));
                panel_side.setMinimumSize(new java.awt.Dimension(250, 100));

                jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
                jScrollPane1.setBorder(null);

                menus.setBackground(new java.awt.Color(255, 255, 255));
                menus.setLayout(new javax.swing.BoxLayout(menus, javax.swing.BoxLayout.Y_AXIS));
                jScrollPane1.setViewportView(menus);

                javax.swing.GroupLayout panel_sideLayout = new javax.swing.GroupLayout(panel_side);
                panel_side.setLayout(panel_sideLayout);
                panel_sideLayout.setHorizontalGroup(
                        panel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_sideLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE))
                );
                panel_sideLayout.setVerticalGroup(
                        panel_sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                );

                getContentPane().add(panel_side, java.awt.BorderLayout.LINE_START);

                panel_content.setBackground(new java.awt.Color(255, 255, 255));

                panel_Utama.setBackground(new java.awt.Color(255, 255, 255));
                panel_Utama.setLayout(new javax.swing.BoxLayout(panel_Utama, javax.swing.BoxLayout.LINE_AXIS));

                javax.swing.GroupLayout panel_contentLayout = new javax.swing.GroupLayout(panel_content);
                panel_content.setLayout(panel_contentLayout);
                panel_contentLayout.setHorizontalGroup(
                        panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_contentLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panel_Utama, javax.swing.GroupLayout.DEFAULT_SIZE, 1525, Short.MAX_VALUE))
                );
                panel_contentLayout.setVerticalGroup(
                        panel_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel_Utama, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                );

                getContentPane().add(panel_content, java.awt.BorderLayout.CENTER);

                setSize(new java.awt.Dimension(1589, 731));
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        panel_Utama.add(new Cashier());
        panel_Utama.repaint();
        panel_Utama.revalidate();
    }//GEN-LAST:event_formWindowOpened

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(homeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(homeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(homeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(homeApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            @Override
////            public void run() {
////                new homeApp().setVisible(true);
////            }
////        });
//    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel Separate;
        private javax.swing.JLabel Seperate;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JLabel labelDate;
        private javax.swing.JLabel labelIcon;
        private javax.swing.JLabel labelIdEmployee;
        private javax.swing.JLabel labelMinimarket;
        private javax.swing.JLabel labelName;
        private javax.swing.JLabel labelPicture;
        private javax.swing.JLabel labelRole;
        private javax.swing.JLabel labelTime;
        private javax.swing.JPanel menus;
        private javax.swing.JPanel panel_Utama;
        private javax.swing.JPanel panel_content;
        private javax.swing.JPanel panel_nav;
        private javax.swing.JPanel panel_side;
        // End of variables declaration//GEN-END:variables

   private void execute() {
    //inisiasi gambar icon
    //iconMenu
   ImageIcon cashier = new ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/homeApp/cashier.png"));
   ImageIcon iconMaster = new ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/homeApp/master.png"));
   ImageIcon iconTransaksi = new ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/homeApp/transaksi.png"));
   ImageIcon iconReport = new ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/homeApp/report.png"));
   ImageIcon iconAccount = new ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/homeApp/account.png"));
   
   
   //icon subMenu
   //submenu Pengaturan
    ImageIcon accountSetting = new ImageIcon( getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/homeApp/userSet.png"));
     ImageIcon logout = new ImageIcon( getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/homeApp/logout.png"));
    
    //submenu Other
    ImageIcon iconBarang = new ImageIcon( getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/homeApp/subMaster.png"));
    
   
    
   //Membuaat SubMenu
   //subMenu Master
   menuIcon subMaster1= new menuIcon(null,true,iconBarang,"Data Barang",new ActionListener() {
       @Override
       public void actionPerformed(ActionEvent e) {
        panel_Utama.removeAll();
        panel_Utama.add(new itemForm());
        panel_Utama.repaint();
        panel_Utama.revalidate();
       }
       
   });
   menuIcon subMaster2= new menuIcon(null,true,iconBarang,"Data Karyawan", new ActionListener() {
	   @Override
	   public void actionPerformed(ActionEvent e) {
		panel_Utama.removeAll();
		panel_Utama.add(new employeeForm());
		panel_Utama.repaint();
		panel_Utama.revalidate();
		}
   });
   menuIcon subMaster3= new menuIcon(null,true,iconBarang,"Barang3",null);
   
   
   //subMenu Transaksi
   menuIcon transaksi1= new menuIcon(null,true,iconBarang,"Transaksi1",null);
   menuIcon transaksi2= new menuIcon(null,true,iconBarang,"Transaksi2",null);
   menuIcon transaksi3= new menuIcon(null,true,iconBarang,"Transaksi3",null);
   
   //submenu pengaturan
   menuIcon accountSet = new menuIcon(null, true, accountSetting, "Pengaturan Akun", null);
   menuIcon logoutSet = new menuIcon(null, true, logout, "logout", new ActionListener() {
	   @Override
	   public void actionPerformed(ActionEvent e) {
		   dispose();
		   new edu.unindra.kkp_kelompok4.login.formLogin().setVisible(true);  
	   }
   });
   
   //Membuat menu
   menuIcon menuCashier = new menuIcon(cashier,false,null,"Cashier",new ActionListener() {
       @Override
       public void actionPerformed(ActionEvent e) {
        panel_Utama.removeAll();
        panel_Utama.add(new Cashier());
        panel_Utama.repaint();
        panel_Utama.revalidate();
       }
   });
   
   menuIcon menuMaster = new menuIcon(iconMaster,false,null,"Master",null,subMaster1,subMaster2,subMaster3);
   menuIcon menuTransaksi= new menuIcon(iconTransaksi,false,null,"Transaksi",null,transaksi1,transaksi2,transaksi3);
   menuIcon menuReport= new menuIcon(iconReport,false,null,"Laporan",null);
   menuIcon Account= new menuIcon(iconAccount,false,null,"Akun",null,accountSet,logoutSet);
   
   
   
   //menambahkan menu
   addMenu(menuCashier,menuMaster,menuTransaksi,menuReport, Account);
 
   
    }
   
   
   private void timeLabel() {
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    Thread thread = new Thread(() -> {
        while (true) {
            LocalDateTime currentTime = LocalDateTime.now();

            try {
                Thread.sleep(1000); 
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            String formattedTime = formatter.format(currentTime);
            EventQueue.invokeLater(() -> labelTime.setText(formattedTime));
        }
    });
    thread.start();
}

    private void addMenu(menuIcon...menu){
        for (int i = 0; i< menu.length;i++){
            menus.add(menu[i]);
            ArrayList<menuIcon>subMenu =menu[i].getSubMenu();
            for(menuIcon m : subMenu){
                addMenu(m);
            }
        }
        menus.revalidate();
    }
    
//    private Image createRoundedImage(Image image) {
//int imageSize = Math.min(image.getWidth(null), image.getHeight(null));
//    BufferedImage roundedImage = new BufferedImage(imageSize, imageSize, BufferedImage.TYPE_INT_ARGB);
//    Graphics2D g2d = roundedImage.createGraphics();
//    g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
//    g2d.setClip(new Ellipse2D.Float(0, 0, imageSize, imageSize));
//    g2d.drawImage(image, 0, 0, imageSize, imageSize, null);
//    g2d.dispose();
//    return roundedImage;
//}
    

}
