package edu.unindra.kkp_kelompok4.home;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;

/**
 *
 * @author fadli
 */
public class menuIcon extends javax.swing.JPanel {

    /**
     * @return the subMenu
     */
    public ArrayList<menuIcon> getSubMenu() {
        return subMenu;
    }

    private final ArrayList<menuIcon>subMenu = new ArrayList<>();
    /**
     * Creates new form menuIcon
     */
    private ActionListener act;
    public menuIcon(Icon icon,boolean sbm,Icon iconSub,String menuName,ActionListener act,menuIcon...subMenu) {
        initComponents();
        
        lb_Icon.setIcon(icon);
        lb_menuname.setText(menuName);
        lb_iconSub.setIcon(iconSub);
        lb_iconSub.setVisible(sbm);
        
        if(act != null){
            this.act = act;
        }
        this.setSize(new Dimension(Integer.MAX_VALUE, 45));
        this.setMaximumSize(new Dimension (Integer.MAX_VALUE,45));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE,45));
        for(int i = 0; i< subMenu.length; i++){
            this.subMenu.add(subMenu[i]);
            subMenu[i].setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                lb_menuname = new javax.swing.JLabel();
                lb_iconSub = new javax.swing.JLabel();
                lb_Icon = new javax.swing.JLabel();

                setBackground(new java.awt.Color(255, 255, 255));
                addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                formMousePressed(evt);
                        }
                });

                lb_menuname.setText("Menu Item...");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lb_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_iconSub, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lb_menuname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb_Icon, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lb_iconSub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lb_menuname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
        }// </editor-fold>//GEN-END:initComponents
private boolean showing = false;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        setBackground(new java.awt.Color(255,255,255));
        if (showing){
            hideMenu();
        }else{
            showMenu();
        }
        if(act != null){
            act.actionPerformed(null);
        }
    }//GEN-LAST:event_formMousePressed


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel lb_Icon;
        private javax.swing.JLabel lb_iconSub;
        private javax.swing.JLabel lb_menuname;
        // End of variables declaration//GEN-END:variables

    private void hideMenu() {
       new Thread (new Runnable(){
           public void run(){
               for (int i = subMenu.size() - 1;i>=0;i--){
                   sleep();
                   subMenu.get(i).setVisible(false);
                   subMenu.get(i).hideMenu();
                   
               }
               getParent().repaint();
               getParent().revalidate();
               showing = false;
           }
       }).start();
    }

    private void showMenu() {
        new Thread (new Runnable(){
           public void run(){
               for (int i = 0; i<subMenu.size();i++){
                   sleep();
                   subMenu.get(i).setVisible(true);
                   
               }
               
               showing = true;
                getParent().repaint();
               getParent().revalidate();
           }  
        }).start();
    }

            private void sleep() {
            try{
                Thread.sleep(1);
                
            }catch(Exception e){
                
            }
            }
}            
     
