/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.unindra.kkp_kelompok4.master;

import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import edu.unindra.kkp_kelompok4.resource.koneksi;
/**
 *
 * @author ripal
 */
public class employeeForm extends javax.swing.JPanel {

    /**
     * Creates new form itemForm
     */
	 private Connection conn = new koneksi().connect();
	 private DefaultTableModel tableModel;
    public employeeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                btnGroupGender = new javax.swing.ButtonGroup();
                mainPanel = new javax.swing.JPanel();
                dataPanel = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                employeeTable = new javax.swing.JTable();
                addEmployeePanel = new javax.swing.JPanel();
                titleLabel = new javax.swing.JLabel();
                addButton = new javax.swing.JButton();
                addPanel = new javax.swing.JPanel();
                titleLabel1 = new javax.swing.JLabel();
                cancelButton = new javax.swing.JButton();
                jScrollPane3 = new javax.swing.JScrollPane();
                jcRole = new javax.swing.JPanel();
                employeeId = new javax.swing.JLabel();
                jtIdEmployee = new javax.swing.JTextField();
                employeeName2 = new javax.swing.JLabel();
                jtNameEmployee = new javax.swing.JTextField();
                Gender = new javax.swing.JLabel();
                male = new javax.swing.JRadioButton();
                female = new javax.swing.JRadioButton();
                placeOfBirth = new javax.swing.JLabel();
                jtPlaceOfBirth = new javax.swing.JTextField();
                dateOfBirth = new javax.swing.JLabel();
                address = new javax.swing.JLabel();
                jScrollPane4 = new javax.swing.JScrollPane();
                tfAddress = new javax.swing.JTextArea();
                email = new javax.swing.JLabel();
                jtEmail1 = new javax.swing.JTextField();
                username = new javax.swing.JLabel();
                jtUsername = new javax.swing.JTextField();
                password = new javax.swing.JLabel();
                jtPassword = new javax.swing.JTextField();
                phoneNumber = new javax.swing.JLabel();
                jtPhoneNumber = new javax.swing.JTextField();
                lRole = new javax.swing.JLabel();
                jComboBox1 = new javax.swing.JComboBox<>();
                jDateChooser1 = new com.toedter.calendar.JDateChooser();
                saveButton = new javax.swing.JButton();
                selectedPanel = new javax.swing.JPanel();
                selectPanel = new javax.swing.JPanel();
                titleLabel2 = new javax.swing.JLabel();
                editButton = new javax.swing.JButton();
                deleteButton = new javax.swing.JButton();
                cancelButton1 = new javax.swing.JButton();
                addedEmployee = new javax.swing.JPanel();
                addEmployeePanelTemp = new javax.swing.JPanel();
                titleLabel5 = new javax.swing.JLabel();
                addButton1 = new javax.swing.JButton();

                setLayout(new java.awt.CardLayout());

                mainPanel.setLayout(new java.awt.CardLayout());

                employeeTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                employeeTableMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(employeeTable);

                titleLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                titleLabel.setText("Data Karyawan");

                addButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                addButton.setText("Tambah");
                addButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout addEmployeePanelLayout = new javax.swing.GroupLayout(addEmployeePanel);
                addEmployeePanel.setLayout(addEmployeePanelLayout);
                addEmployeePanelLayout.setHorizontalGroup(
                        addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addEmployeePanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(titleLabel)
                                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(752, Short.MAX_VALUE)))
                );
                addEmployeePanelLayout.setVerticalGroup(
                        addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 134, Short.MAX_VALUE)
                        .addGroup(addEmployeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addEmployeePanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(17, Short.MAX_VALUE)))
                );

                javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
                dataPanel.setLayout(dataPanelLayout);
                dataPanelLayout.setHorizontalGroup(
                        dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanelLayout.createSequentialGroup()
                                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(addEmployeePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 945, Short.MAX_VALUE))
                                .addGap(0, 367, Short.MAX_VALUE))
                );
                dataPanelLayout.setVerticalGroup(
                        dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanelLayout.createSequentialGroup()
                                .addComponent(addEmployeePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(200, Short.MAX_VALUE))
                );

                mainPanel.add(dataPanel, "card2");

                titleLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                titleLabel1.setText("Tambah karyawan");

                cancelButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                cancelButton.setText("Batal");
                cancelButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonActionPerformed(evt);
                        }
                });

                jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

                jcRole.setPreferredSize(new java.awt.Dimension(761, 1000));
                jcRole.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                employeeId.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                employeeId.setText("ID Karyawan");
                jcRole.add(employeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 31));
                jcRole.add(jtIdEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 234, 33));

                employeeName2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                employeeName2.setText("Nama Karyawan");
                jcRole.add(employeeName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 31));
                jcRole.add(jtNameEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 234, 33));

                Gender.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                Gender.setText("Jenisk Kelamain");
                jcRole.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 31));

                btnGroupGender.add(male);
                male.setText("Laki-Laki");
                jcRole.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

                btnGroupGender.add(female);
                female.setText("Perempuan");
                jcRole.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

                placeOfBirth.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                placeOfBirth.setText("Tempat Lahir");
                jcRole.add(placeOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 31));
                jcRole.add(jtPlaceOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 231, 33));

                dateOfBirth.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                dateOfBirth.setText("Tanggal Lahir");
                jcRole.add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, 31));

                address.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                address.setText("Alamat");
                jcRole.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 31));

                tfAddress.setColumns(20);
                tfAddress.setRows(5);
                jScrollPane4.setViewportView(tfAddress);

                jcRole.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 223, 104));

                email.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                email.setText("Email");
                jcRole.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, 31));
                jcRole.add(jtEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 231, 33));

                username.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                username.setText("Username");
                jcRole.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, -1, 31));
                jcRole.add(jtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 231, 33));

                password.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                password.setText("Password");
                jcRole.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, 31));
                jcRole.add(jtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 231, 33));

                phoneNumber.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                phoneNumber.setText("No HP");
                jcRole.add(phoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, 31));

                jtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jtPhoneNumberActionPerformed(evt);
                        }
                });
                jcRole.add(jtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 231, 33));

                lRole.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                lRole.setText("Role");
                jcRole.add(lRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, -1, 31));

                jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Owner", "Cashir" }));
                jcRole.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, 104, -1));
                jcRole.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 231, 33));

                jScrollPane3.setViewportView(jcRole);

                saveButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                saveButton.setText("Simpan");
                saveButton.setToolTipText("");
                saveButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                saveButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
                addPanel.setLayout(addPanelLayout);
                addPanelLayout.setHorizontalGroup(
                        addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titleLabel1)
                                        .addGroup(addPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(addPanelLayout.createSequentialGroup()
                                                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(610, Short.MAX_VALUE))
                );
                addPanelLayout.setVerticalGroup(
                        addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );

                mainPanel.add(addPanel, "card2");

                titleLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                titleLabel2.setText("Data Karyawan");

                editButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                editButton.setText("Edit");
                editButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                editButtonActionPerformed(evt);
                        }
                });

                deleteButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                deleteButton.setText("Hapus");
                deleteButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                deleteButtonActionPerformed(evt);
                        }
                });

                cancelButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                cancelButton1.setText("Batal");
                cancelButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout selectPanelLayout = new javax.swing.GroupLayout(selectPanel);
                selectPanel.setLayout(selectPanelLayout);
                selectPanelLayout.setHorizontalGroup(
                        selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 969, Short.MAX_VALUE)
                        .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(selectPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(titleLabel2)
                                                .addGroup(selectPanelLayout.createSequentialGroup()
                                                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(654, Short.MAX_VALUE)))
                );
                selectPanelLayout.setVerticalGroup(
                        selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 160, Short.MAX_VALUE)
                        .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(selectPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(titleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(selectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                );

                javax.swing.GroupLayout selectedPanelLayout = new javax.swing.GroupLayout(selectedPanel);
                selectedPanel.setLayout(selectedPanelLayout);
                selectedPanelLayout.setHorizontalGroup(
                        selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(selectedPanelLayout.createSequentialGroup()
                                .addComponent(selectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 343, Short.MAX_VALUE))
                );
                selectedPanelLayout.setVerticalGroup(
                        selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(selectedPanelLayout.createSequentialGroup()
                                .addComponent(selectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 697, Short.MAX_VALUE))
                );

                mainPanel.add(selectedPanel, "card2");

                titleLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                titleLabel5.setText("Data Karyawan");

                addButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                addButton1.setText("Tambah");
                addButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout addEmployeePanelTempLayout = new javax.swing.GroupLayout(addEmployeePanelTemp);
                addEmployeePanelTemp.setLayout(addEmployeePanelTempLayout);
                addEmployeePanelTempLayout.setHorizontalGroup(
                        addEmployeePanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 1312, Short.MAX_VALUE)
                        .addGroup(addEmployeePanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addEmployeePanelTempLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(addEmployeePanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(titleLabel5)
                                                .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(752, Short.MAX_VALUE)))
                );
                addEmployeePanelTempLayout.setVerticalGroup(
                        addEmployeePanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 134, Short.MAX_VALUE)
                        .addGroup(addEmployeePanelTempLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(addEmployeePanelTempLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(titleLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(addButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(17, Short.MAX_VALUE)))
                );

                javax.swing.GroupLayout addedEmployeeLayout = new javax.swing.GroupLayout(addedEmployee);
                addedEmployee.setLayout(addedEmployeeLayout);
                addedEmployeeLayout.setHorizontalGroup(
                        addedEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(addEmployeePanelTemp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                addedEmployeeLayout.setVerticalGroup(
                        addedEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addedEmployeeLayout.createSequentialGroup()
                                .addComponent(addEmployeePanelTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 723, Short.MAX_VALUE))
                );

                mainPanel.add(addedEmployee, "card2");

                add(mainPanel, "card2");
        }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
       addBt();
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        mainPanel.removeAll();
        mainValidate();
        mainPanel.add(dataPanel);
	mainValidate();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked
        	addEmployeePanel.removeAll();
	addEmployeePanel.add(selectPanel);
        addEmployeePanel.repaint();
	addEmployeePanel.revalidate();
	dataPanel.repaint();
	dataPanel.revalidate();
	mainValidate();


    }//GEN-LAST:event_employeeTableMouseClicked

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
	addEmployeePanel.removeAll();
	addEmployeePanel.add(addEmployeePanelTemp);
        addEmployeePanel.repaint();
	addEmployeePanel.revalidate();
	dataPanel.repaint();
	dataPanel.revalidate();
	mainValidate();
    }//GEN-LAST:event_cancelButton1ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

        private void jtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtPhoneNumberActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jtPhoneNumberActionPerformed

        private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed
                addBt();
        }//GEN-LAST:event_addButton1ActionPerformed

private void addBt(){
	mainPanel.removeAll();
        mainValidate();
        
        mainPanel.add(addPanel);
        mainValidate();
}
private void mainValidate(){
        mainPanel.repaint();
        mainPanel.revalidate();
}

//protected void datatable(){
//        Object[] Baris ={"ID Karyawan","Nama Karyawan","Jenis Kelamin","Tempat Lahir","Tanggal Lahir","Alamat","Email","No Telp","Role"};
//        tableModel = new DefaultTableModel(null, Baris);
//        employeeTable.setModel(tableModel);
//        String sql ="Select * From employeeTable";
//        try {
//            java.sql.Statement stat = conn.createStatement();
//            ResultSet hasil = stat.executeQuery(sql);
//            while (hasil.next()){
//                String a = hasil.getString("IdEmployee");
//                String b = hasil.getString("nameEmployee");
//                String c = hasil.getString("Gender");
//                String d = hasil.getString("place_of_birth");
//                String e = hasil.getString("date_of_birth");
//		String f = hasil.getString("address");
//		String g = hasil.getString("email");
//		String h = hasil.getString("phoneNumber");
//		String i = hasil.getString("role");
//                
//                String[] data = {a,b,c,d,e,f,g,h,i};
//                tableModel.addRow(data);
//            }
//        } catch (Exception e) {
//            System.out.println("Input gagal : "+e);
//        }
//        }
    


        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JLabel Gender;
        private javax.swing.JButton addButton;
        private javax.swing.JButton addButton1;
        private javax.swing.JPanel addEmployeePanel;
        private javax.swing.JPanel addEmployeePanelTemp;
        private javax.swing.JPanel addPanel;
        private javax.swing.JPanel addedEmployee;
        private javax.swing.JLabel address;
        private javax.swing.ButtonGroup btnGroupGender;
        private javax.swing.JButton cancelButton;
        private javax.swing.JButton cancelButton1;
        private javax.swing.JPanel dataPanel;
        private javax.swing.JLabel dateOfBirth;
        private javax.swing.JButton deleteButton;
        private javax.swing.JButton editButton;
        private javax.swing.JLabel email;
        private javax.swing.JLabel employeeId;
        private javax.swing.JLabel employeeName2;
        private javax.swing.JTable employeeTable;
        private javax.swing.JRadioButton female;
        private javax.swing.JComboBox<String> jComboBox1;
        private com.toedter.calendar.JDateChooser jDateChooser1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane3;
        private javax.swing.JScrollPane jScrollPane4;
        private javax.swing.JPanel jcRole;
        private javax.swing.JTextField jtEmail1;
        private javax.swing.JTextField jtIdEmployee;
        private javax.swing.JTextField jtNameEmployee;
        private javax.swing.JTextField jtPassword;
        private javax.swing.JTextField jtPhoneNumber;
        private javax.swing.JTextField jtPlaceOfBirth;
        private javax.swing.JTextField jtUsername;
        private javax.swing.JLabel lRole;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JRadioButton male;
        private javax.swing.JLabel password;
        private javax.swing.JLabel phoneNumber;
        private javax.swing.JLabel placeOfBirth;
        private javax.swing.JButton saveButton;
        private javax.swing.JPanel selectPanel;
        private javax.swing.JPanel selectedPanel;
        private javax.swing.JTextArea tfAddress;
        private javax.swing.JLabel titleLabel;
        private javax.swing.JLabel titleLabel1;
        private javax.swing.JLabel titleLabel2;
        private javax.swing.JLabel titleLabel5;
        private javax.swing.JLabel username;
        // End of variables declaration//GEN-END:variables
}
