/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.unindra.kkp_kelompok4.master;

/**
 *
 * @author ripal
 */
public class itemForm extends javax.swing.JPanel {

    /**
     * Creates new form itemForm
     */
    public itemForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                mainPanel = new javax.swing.JPanel();
                dataPanel = new javax.swing.JPanel();
                titleLabel = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                itemTable = new javax.swing.JTable();
                addButton = new javax.swing.JButton();
                addPanel = new javax.swing.JPanel();
                titleLabel1 = new javax.swing.JLabel();
                cancelButton = new javax.swing.JButton();
                addItem = new javax.swing.JPanel();
                kodeBarang = new javax.swing.JLabel();
                jtKodebarang = new javax.swing.JTextField();
                namaBarang = new javax.swing.JLabel();
                jtNamabarang = new javax.swing.JTextField();
                jumlah = new javax.swing.JLabel();
                jtJumlah = new javax.swing.JTextField();
                jenisBarang = new javax.swing.JLabel();
                cbJenisbarang = new javax.swing.JComboBox<>();
                suppplierLabel = new javax.swing.JLabel();
                cbSupplier = new javax.swing.JComboBox<>();
                saveButton = new javax.swing.JButton();
                selectedPanel = new javax.swing.JPanel();
                titleLabel2 = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                itemTable1 = new javax.swing.JTable();
                editButton = new javax.swing.JButton();
                deleteButton = new javax.swing.JButton();
                cancelButton1 = new javax.swing.JButton();

                setLayout(new java.awt.CardLayout());

                mainPanel.setLayout(new java.awt.CardLayout());

                titleLabel.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                titleLabel.setText("Data Barang");

                itemTable.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                itemTable.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                itemTableMouseClicked(evt);
                        }
                });
                jScrollPane1.setViewportView(itemTable);

                addButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                addButton.setText("Tambah");
                addButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                addButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
                dataPanel.setLayout(dataPanelLayout);
                dataPanelLayout.setHorizontalGroup(
                        dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanelLayout.createSequentialGroup()
                                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(dataPanelLayout.createSequentialGroup()
                                                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(titleLabel)
                                                        .addGroup(dataPanelLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(dataPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1288, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                dataPanelLayout.setVerticalGroup(
                        dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dataPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                                .addGap(95, 95, 95))
                );

                mainPanel.add(dataPanel, "card2");

                titleLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                titleLabel1.setText("Tambah Data Barang");

                cancelButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                cancelButton.setText("Batal");
                cancelButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButtonActionPerformed(evt);
                        }
                });

                kodeBarang.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                kodeBarang.setText("Kode Barang");

                namaBarang.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                namaBarang.setText("Nama Barang");

                jumlah.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                jumlah.setText("Jumlah");

                jenisBarang.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                jenisBarang.setText("Jenis Barang");

                cbJenisbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                suppplierLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                suppplierLabel.setText("Supplier");

                cbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

                javax.swing.GroupLayout addItemLayout = new javax.swing.GroupLayout(addItem);
                addItem.setLayout(addItemLayout);
                addItemLayout.setHorizontalGroup(
                        addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addItemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(kodeBarang)
                                        .addComponent(namaBarang)
                                        .addComponent(jumlah)
                                        .addComponent(jenisBarang)
                                        .addComponent(suppplierLabel)
                                        .addComponent(cbJenisbarang, 0, 1174, Short.MAX_VALUE)
                                        .addComponent(jtJumlah)
                                        .addComponent(jtNamabarang)
                                        .addComponent(jtKodebarang)
                                        .addComponent(cbSupplier, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(120, Short.MAX_VALUE))
                );
                addItemLayout.setVerticalGroup(
                        addItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addItemLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(kodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtKodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(namaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbJenisbarang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(suppplierLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(89, Short.MAX_VALUE))
                );

                saveButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                saveButton.setText("Simpan");
                saveButton.setToolTipText("");
                saveButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                saveButtonActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
                addPanel.setLayout(addPanelLayout);
                addPanelLayout.setHorizontalGroup(
                        addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addPanelLayout.createSequentialGroup()
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(titleLabel1)
                                        .addGroup(addPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(addItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(addPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                addPanelLayout.setVerticalGroup(
                        addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(addItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                mainPanel.add(addPanel, "card2");

                titleLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                titleLabel2.setText("Data Barang");

                itemTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane2.setViewportView(itemTable1);

                editButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                editButton.setText("Edit");
                editButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                editButtonActionPerformed(evt);
                        }
                });

                deleteButton.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                deleteButton.setText("Hapus");
                deleteButton.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                deleteButtonActionPerformed(evt);
                        }
                });

                cancelButton1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                cancelButton1.setText("Batal");
                cancelButton1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cancelButton1ActionPerformed(evt);
                        }
                });

                javax.swing.GroupLayout selectedPanelLayout = new javax.swing.GroupLayout(selectedPanel);
                selectedPanel.setLayout(selectedPanelLayout);
                selectedPanelLayout.setHorizontalGroup(
                        selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(selectedPanelLayout.createSequentialGroup()
                                .addGroup(selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(selectedPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1288, Short.MAX_VALUE))
                                        .addGroup(selectedPanelLayout.createSequentialGroup()
                                                .addGroup(selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(titleLabel2)
                                                        .addGroup(selectedPanelLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                selectedPanelLayout.setVerticalGroup(
                        selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(selectedPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(titleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(selectedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
                );

                mainPanel.add(selectedPanel, "card2");

                add(mainPanel, "card2");
        }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        mainPanel.removeAll();
        mainValidate();
        
        mainPanel.add(addPanel);
        mainValidate();
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        mainPanel.removeAll();
        mainValidate();
        
        mainPanel.add(dataPanel);
        mainValidate();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void cancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton1ActionPerformed
        mainPanel.removeAll();
        mainValidate();
        
        mainPanel.add(dataPanel);
        mainValidate();
    }//GEN-LAST:event_cancelButton1ActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void itemTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemTableMouseClicked
        mainPanel.removeAll();
        mainValidate();

        mainPanel.add(selectedPanel);
        mainValidate();
    }//GEN-LAST:event_itemTableMouseClicked

private void mainValidate(){
        mainPanel.repaint();
        mainPanel.revalidate();
}
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton addButton;
        private javax.swing.JPanel addItem;
        private javax.swing.JPanel addPanel;
        private javax.swing.JButton cancelButton;
        private javax.swing.JButton cancelButton1;
        private javax.swing.JComboBox<String> cbJenisbarang;
        private javax.swing.JComboBox<String> cbSupplier;
        private javax.swing.JPanel dataPanel;
        private javax.swing.JButton deleteButton;
        private javax.swing.JButton editButton;
        private javax.swing.JTable itemTable;
        private javax.swing.JTable itemTable1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JLabel jenisBarang;
        private javax.swing.JTextField jtJumlah;
        private javax.swing.JTextField jtKodebarang;
        private javax.swing.JTextField jtNamabarang;
        private javax.swing.JLabel jumlah;
        private javax.swing.JLabel kodeBarang;
        private javax.swing.JPanel mainPanel;
        private javax.swing.JLabel namaBarang;
        private javax.swing.JButton saveButton;
        private javax.swing.JPanel selectedPanel;
        private javax.swing.JLabel suppplierLabel;
        private javax.swing.JLabel titleLabel;
        private javax.swing.JLabel titleLabel1;
        private javax.swing.JLabel titleLabel2;
        // End of variables declaration//GEN-END:variables
}
