/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package edu.unindra.kkp_kelompok4.cashier;

import java.awt.*;
import javax.swing.*;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import edu.unindra.kkp_kelompok4.lock.lockApp;
/**
 *
 * @author ripal
 */
public class Cashier extends javax.swing.JPanel {

    /**
     * Creates new form Cashier
     */
    public Cashier() {
        initComponents();
//        Colorheader();
//        tfItem.setText("Masukan Kode Barang atau Nama Barang");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                MainPanel = new javax.swing.JPanel();
                addPanel = new javax.swing.JPanel();
                tfItem = new javax.swing.JTextField();
                btAdd = new javax.swing.JLabel();
                sumPanel = new javax.swing.JPanel();
                totalLabel = new javax.swing.JLabel();
                priceLabel = new javax.swing.JLabel();
                buttonPanel = new javax.swing.JPanel();
                newTransaction = new javax.swing.JLabel();
                Seperate = new javax.swing.JLabel();
                openTransaction = new javax.swing.JLabel();
                Seperate1 = new javax.swing.JLabel();
                saveDraft = new javax.swing.JLabel();
                Seperate2 = new javax.swing.JLabel();
                openDraft = new javax.swing.JLabel();
                Seperate3 = new javax.swing.JLabel();
                aboutApp = new javax.swing.JLabel();
                Seperate4 = new javax.swing.JLabel();
                reportBug = new javax.swing.JLabel();
                tablePanel = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                jtListItem = new javax.swing.JTable();
                PaymentPanel = new javax.swing.JPanel();
                PaymentLabel = new javax.swing.JLabel();
                returnsLabel = new javax.swing.JLabel();
                payLabel = new javax.swing.JLabel();
                payLabel1 = new javax.swing.JLabel();
                paidPanel = new javax.swing.JPanel();
                paidField = new javax.swing.JTextField();
                rpLabel2 = new javax.swing.JLabel();
                listMethod = new javax.swing.JComboBox<>();
                shoppingReturns = new javax.swing.JPanel();
                returnsField = new javax.swing.JTextField();
                rpLabel1 = new javax.swing.JLabel();
                jButton1 = new javax.swing.JButton();
                paymentDetails = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jTextField1 = new javax.swing.JTextField();
                jLabel10 = new javax.swing.JLabel();
                jLabel11 = new javax.swing.JLabel();
                jLabel12 = new javax.swing.JLabel();
                jTextField5 = new javax.swing.JTextField();
                jTextField6 = new javax.swing.JTextField();
                jTextField7 = new javax.swing.JTextField();
                lockApp = new javax.swing.JLabel();

                setBackground(new java.awt.Color(255, 255, 255));
                setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                addPanel.setBackground(new java.awt.Color(255, 255, 255));

                tfItem.setForeground(new java.awt.Color(102, 102, 102));
                tfItem.setText("Masukan Kode Barang atau Nama Barang");
                tfItem.setToolTipText("");
                tfItem.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 255)));
                tfItem.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                                tfItemFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                                tfItemFocusLost(evt);
                        }
                });
                tfItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                tfItemActionPerformed(evt);
                        }
                });

                btAdd.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                btAdd.setText("Cari Barang");

                javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
                addPanel.setLayout(addPanelLayout);
                addPanelLayout.setHorizontalGroup(
                        addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btAdd)
                                        .addComponent(tfItem, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(77, Short.MAX_VALUE))
                );
                addPanelLayout.setVerticalGroup(
                        addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(addPanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfItem, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(29, Short.MAX_VALUE))
                );

                MainPanel.add(addPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 120));

                sumPanel.setBackground(new java.awt.Color(255, 255, 255));
                sumPanel.setForeground(new java.awt.Color(0, 0, 255));

                totalLabel.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                totalLabel.setText("Total");

                priceLabel.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
                priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
                priceLabel.setText("Rp. 000, 000");

                javax.swing.GroupLayout sumPanelLayout = new javax.swing.GroupLayout(sumPanel);
                sumPanel.setLayout(sumPanelLayout);
                sumPanelLayout.setHorizontalGroup(
                        sumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sumPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(sumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(sumPanelLayout.createSequentialGroup()
                                                .addComponent(totalLabel)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(sumPanelLayout.createSequentialGroup()
                                                .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 599, Short.MAX_VALUE)
                                                .addGap(164, 164, 164))))
                );
                sumPanelLayout.setVerticalGroup(
                        sumPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(sumPanelLayout.createSequentialGroup()
                                .addComponent(totalLabel)
                                .addGap(31, 31, 31)
                                .addComponent(priceLabel)
                                .addGap(0, 6, Short.MAX_VALUE))
                );

                MainPanel.add(sumPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, 120));

                buttonPanel.setBackground(new java.awt.Color(255, 255, 255));
                buttonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                newTransaction.setBackground(new java.awt.Color(204, 204, 204));
                newTransaction.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                newTransaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                newTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/CashierApp/NewTransation.png"))); // NOI18N
                newTransaction.setText("New Transaction");
                newTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                newTransactionMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                newTransactionMouseExited(evt);
                        }
                });
                buttonPanel.add(newTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 0, 230, 70));

                Seperate.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
                Seperate.setText("|");
                buttonPanel.add(Seperate, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 30, 71));

                openTransaction.setBackground(new java.awt.Color(204, 204, 204));
                openTransaction.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                openTransaction.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                openTransaction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/CashierApp/OpenTransaction.png"))); // NOI18N
                openTransaction.setText("Open Transaction");
                openTransaction.setPreferredSize(new java.awt.Dimension(111, 34));
                openTransaction.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                openTransactionMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                openTransactionMouseExited(evt);
                        }
                });
                buttonPanel.add(openTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, -1, 215, 70));

                Seperate1.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
                Seperate1.setText("|");
                buttonPanel.add(Seperate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 0, -1, 70));

                saveDraft.setBackground(new java.awt.Color(204, 204, 204));
                saveDraft.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                saveDraft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                saveDraft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/CashierApp/Save.png"))); // NOI18N
                saveDraft.setText("Save to draft");
                saveDraft.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                saveDraftMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                saveDraftMouseExited(evt);
                        }
                });
                buttonPanel.add(saveDraft, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 0, 200, 70));

                Seperate2.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
                Seperate2.setText("|");
                buttonPanel.add(Seperate2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 30, 70));

                openDraft.setBackground(new java.awt.Color(204, 204, 204));
                openDraft.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                openDraft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                openDraft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/CashierApp/OpenDraft.png"))); // NOI18N
                openDraft.setText("Open from Draft");
                openDraft.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                openDraftMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                openDraftMouseExited(evt);
                        }
                });
                buttonPanel.add(openDraft, new org.netbeans.lib.awtextra.AbsoluteConstraints(682, 0, 200, 70));

                Seperate3.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
                Seperate3.setText("|");
                buttonPanel.add(Seperate3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, -1, 70));

                aboutApp.setBackground(new java.awt.Color(204, 204, 204));
                aboutApp.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                aboutApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                aboutApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/CashierApp/About.png"))); // NOI18N
                aboutApp.setText("About App");
                aboutApp.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                aboutAppMouseClicked(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                aboutAppMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                aboutAppMouseExited(evt);
                        }
                });
                buttonPanel.add(aboutApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(887, 0, 180, 70));

                Seperate4.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
                Seperate4.setText("|");
                buttonPanel.add(Seperate4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1055, 0, -1, 70));

                reportBug.setBackground(new java.awt.Color(204, 204, 204));
                reportBug.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                reportBug.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                reportBug.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/CashierApp/Report.png"))); // NOI18N
                reportBug.setText("Report Bug");
                reportBug.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                reportBugMouseClicked(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                reportBugMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                reportBugMouseExited(evt);
                        }
                });
                buttonPanel.add(reportBug, new org.netbeans.lib.awtextra.AbsoluteConstraints(1072, 0, 200, 70));

                MainPanel.add(buttonPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1300, 70));

                tablePanel.setBackground(new java.awt.Color(255, 255, 255));

                jtListItem.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane1.setViewportView(jtListItem);

                javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
                tablePanel.setLayout(tablePanelLayout);
                tablePanelLayout.setHorizontalGroup(
                        tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(tablePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE))
                );
                tablePanelLayout.setVerticalGroup(
                        tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                MainPanel.add(tablePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 890, 370));

                PaymentPanel.setBackground(new java.awt.Color(0, 0, 255));
                PaymentPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
                PaymentPanel.setForeground(new java.awt.Color(51, 0, 204));
                PaymentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                PaymentLabel.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
                PaymentLabel.setForeground(new java.awt.Color(255, 255, 255));
                PaymentLabel.setText("Payment");
                PaymentPanel.add(PaymentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 40));

                returnsLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                returnsLabel.setForeground(new java.awt.Color(255, 255, 255));
                returnsLabel.setText("Kembalian");
                PaymentPanel.add(returnsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, 20));

                payLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                payLabel.setForeground(new java.awt.Color(255, 255, 255));
                payLabel.setText("Metode Pembayaran");
                PaymentPanel.add(payLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, 20));

                payLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
                payLabel1.setForeground(new java.awt.Color(255, 255, 255));
                payLabel1.setText("Uang yang dibayar");
                PaymentPanel.add(payLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, 20));

                paidPanel.setBackground(new java.awt.Color(204, 204, 204));

                paidField.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                paidField.setToolTipText("");
                paidField.setBorder(null);
                paidField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                paidFieldActionPerformed(evt);
                        }
                });

                rpLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                rpLabel2.setText("Rp.");

                javax.swing.GroupLayout paidPanelLayout = new javax.swing.GroupLayout(paidPanel);
                paidPanel.setLayout(paidPanelLayout);
                paidPanelLayout.setHorizontalGroup(
                        paidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paidPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rpLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(paidField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                paidPanelLayout.setVerticalGroup(
                        paidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paidPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(paidPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(paidField)
                                        .addComponent(rpLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                PaymentPanel.add(paidPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 260, 50));

                listMethod.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                listMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "QRIS", "BANK TRANSFERT", "DEBIT", "OTHER" }));
                listMethod.setBorder(null);
                PaymentPanel.add(listMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 260, 50));

                shoppingReturns.setBackground(new java.awt.Color(204, 204, 204));

                returnsField.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                returnsField.setToolTipText("");
                returnsField.setBorder(null);
                returnsField.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                returnsFieldActionPerformed(evt);
                        }
                });

                rpLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
                rpLabel1.setText("Rp.");

                javax.swing.GroupLayout shoppingReturnsLayout = new javax.swing.GroupLayout(shoppingReturns);
                shoppingReturns.setLayout(shoppingReturnsLayout);
                shoppingReturnsLayout.setHorizontalGroup(
                        shoppingReturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shoppingReturnsLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rpLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(returnsField, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                shoppingReturnsLayout.setVerticalGroup(
                        shoppingReturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(shoppingReturnsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(shoppingReturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(returnsField)
                                        .addComponent(rpLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                PaymentPanel.add(shoppingReturns, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 260, 50));

                jButton1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
                jButton1.setForeground(new java.awt.Color(0, 0, 255));
                jButton1.setText("Bayar");
                PaymentPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 290, 70));

                MainPanel.add(PaymentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, 420, 460));

                paymentDetails.setBackground(new java.awt.Color(0, 0, 255));

                jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(255, 255, 255));
                jLabel1.setText("Jumlah Item");

                jTextField1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                jTextField1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField1ActionPerformed(evt);
                        }
                });

                jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                jLabel10.setForeground(new java.awt.Color(255, 255, 255));
                jLabel10.setText("Diskon");

                jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                jLabel11.setForeground(new java.awt.Color(255, 255, 255));
                jLabel11.setText("Sub total");

                jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
                jLabel12.setForeground(new java.awt.Color(255, 255, 255));
                jLabel12.setText("Pajak");

                jTextField5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                jTextField5.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField5ActionPerformed(evt);
                        }
                });

                jTextField6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                jTextField6.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField6ActionPerformed(evt);
                        }
                });

                jTextField7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
                jTextField7.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jTextField7ActionPerformed(evt);
                        }
                });

                lockApp.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
                lockApp.setForeground(new java.awt.Color(255, 255, 255));
                lockApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lockApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/CashierApp/keyWhite.png"))); // NOI18N
                lockApp.setText("<html>\nLock<br>App\n</html>");
                lockApp.setPreferredSize(new java.awt.Dimension(111, 34));
                lockApp.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                lockAppMouseClicked(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                lockAppMouseEntered(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                lockAppMouseExited(evt);
                        }
                });

                javax.swing.GroupLayout paymentDetailsLayout = new javax.swing.GroupLayout(paymentDetails);
                paymentDetails.setLayout(paymentDetailsLayout);
                paymentDetailsLayout.setHorizontalGroup(
                        paymentDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paymentDetailsLayout.createSequentialGroup()
                                .addComponent(lockApp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                                .addGroup(paymentDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(paymentDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel11))
                                .addGap(37, 37, 37)
                                .addGroup(paymentDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10))
                                .addGap(33, 33, 33)
                                .addGroup(paymentDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12)))
                );
                paymentDetailsLayout.setVerticalGroup(
                        paymentDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(paymentDetailsLayout.createSequentialGroup()
                                .addGroup(paymentDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(paymentDetailsLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addGroup(paymentDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel12))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(paymentDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(paymentDetailsLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lockApp, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(17, Short.MAX_VALUE))
                );

                MainPanel.add(paymentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 890, 100));

                add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));
        }// </editor-fold>//GEN-END:initComponents

    private void tfItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfItemActionPerformed

    private void tfItemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfItemFocusLost
        String itemText = tfItem.getText();
        if (itemText.equals("")){
            tfItem.setForeground(new Color(102,102,102));
            tfItem.setText("Masukan Kode Barang atau Nama Barang");
        }
    }//GEN-LAST:event_tfItemFocusLost

    private void tfItemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfItemFocusGained
        String itemText = tfItem.getText();
        if (itemText.equals("Masukan Kode Barang atau Nama Barang")){
            tfItem.setForeground(new Color(102,102,102));
            tfItem.setText("");
        }
    }//GEN-LAST:event_tfItemFocusGained

    private void paidFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paidFieldActionPerformed

    private void returnsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnsFieldActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void aboutAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutAppMouseClicked
         new aboutApp(null, true).show();
    }//GEN-LAST:event_aboutAppMouseClicked

    private void reportBugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBugMouseClicked
               showBugReportDialog();
    }//GEN-LAST:event_reportBugMouseClicked

    private void reportBugMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBugMouseEntered
//               highlight(labelReportBug);
            reportBug.setOpaque(true);
            reportBug.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_reportBugMouseEntered

    private void reportBugMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportBugMouseExited
//              unhighlight(labelReportBug);
               reportBug.setOpaque(false);
               reportBug.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_reportBugMouseExited

    private void aboutAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutAppMouseEntered
                aboutApp.setOpaque(true);
                aboutApp.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_aboutAppMouseEntered

    private void aboutAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutAppMouseExited
                aboutApp.setOpaque(false);
                aboutApp.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_aboutAppMouseExited

    private void openDraftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openDraftMouseEntered
                openDraft.setOpaque(true);
                openDraft.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_openDraftMouseEntered

    private void openDraftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openDraftMouseExited
                openDraft.setOpaque(false);
                openDraft.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_openDraftMouseExited

    private void openTransactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openTransactionMouseEntered
                openTransaction.setOpaque(true);
                openTransaction.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_openTransactionMouseEntered

    private void openTransactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openTransactionMouseExited
                openTransaction.setOpaque(false);
                openTransaction.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_openTransactionMouseExited

    private void newTransactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newTransactionMouseEntered
                newTransaction.setOpaque(true);
                newTransaction.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_newTransactionMouseEntered

    private void newTransactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newTransactionMouseExited
                newTransaction.setOpaque(false);
                newTransaction.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_newTransactionMouseExited

    private void saveDraftMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveDraftMouseEntered
                saveDraft.setOpaque(true);
                saveDraft.setForeground(new Color(0,0,255));
    }//GEN-LAST:event_saveDraftMouseEntered

    private void saveDraftMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveDraftMouseExited
                saveDraft.setOpaque(false);
                saveDraft.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_saveDraftMouseExited

    private void lockAppMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lockAppMouseEntered
                lockApp.setForeground(Color.red);
                lockApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/CashierApp/keyRed.png")));
    }//GEN-LAST:event_lockAppMouseEntered

    private void lockAppMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lockAppMouseExited
                lockApp.setForeground(Color.white);
                lockApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/unindra/kkp_kelompok4/resource/image/CashierApp/keyWhite.png")));
    }//GEN-LAST:event_lockAppMouseExited

    private void lockAppMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lockAppMouseClicked
                new lockApp(null,true).show();
    }//GEN-LAST:event_lockAppMouseClicked

//    private void Colorheader(){
//        jtListItem.getTableHeader().setBackground(new Color(0,0,255));
//        jtListItem.getTableHeader().setForeground(Color.WHITE);
//    }
   

    
    
    private void showBugReportDialog() {
        int result = JOptionPane.showConfirmDialog(null, "Apakah Anda ingin melaporkan bug pada aplikasi ini?", "Laporkan Bug", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            String email = "kelompok4-unindra@googlegroups.com";
            String subject = "Laporan Bug Minimarket XYZ";
            String body = "Halo,\n\nSaya menemukan bug pada aplikasi Minimarket XYZ. Untuk informasi bugnya mohon membalas email ini.\n\nTerima kasih,\n<your name>";

            String mailtoUri = String.format("mailto:%s?subject=%s&body=%s", email, subject, body);
            try {
                Desktop.getDesktop().browse(new URI(mailtoUri));
                String url = "https://mail.google.com";
                Desktop.getDesktop().browse(new URI(url));
            } catch (IOException | URISyntaxException e) {
                JOptionPane.showMessageDialog(null, "Gagal membuka email client atau Gmail. Silakan laporkan bug secara manual ke " + email, "Laporkan Bug", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
//    private void highlight(JLabel label){
//        setOpaque(true);
//        setForeground(new Color(0,0,255));
//    }
//    
//    private void unhighlight(JLabel label){
//        setOpaque(false);
//        setForeground(new Color(0,0,0));
//    }
   
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel MainPanel;
        private javax.swing.JLabel PaymentLabel;
        private javax.swing.JPanel PaymentPanel;
        private javax.swing.JLabel Seperate;
        private javax.swing.JLabel Seperate1;
        private javax.swing.JLabel Seperate2;
        private javax.swing.JLabel Seperate3;
        private javax.swing.JLabel Seperate4;
        private javax.swing.JLabel aboutApp;
        private javax.swing.JPanel addPanel;
        private javax.swing.JLabel btAdd;
        private javax.swing.JPanel buttonPanel;
        private javax.swing.JButton jButton1;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel10;
        private javax.swing.JLabel jLabel11;
        private javax.swing.JLabel jLabel12;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField jTextField1;
        private javax.swing.JTextField jTextField5;
        private javax.swing.JTextField jTextField6;
        private javax.swing.JTextField jTextField7;
        private javax.swing.JTable jtListItem;
        private javax.swing.JComboBox<String> listMethod;
        private javax.swing.JLabel lockApp;
        private javax.swing.JLabel newTransaction;
        private javax.swing.JLabel openDraft;
        private javax.swing.JLabel openTransaction;
        private javax.swing.JTextField paidField;
        private javax.swing.JPanel paidPanel;
        private javax.swing.JLabel payLabel;
        private javax.swing.JLabel payLabel1;
        private javax.swing.JPanel paymentDetails;
        private javax.swing.JLabel priceLabel;
        private javax.swing.JLabel reportBug;
        private javax.swing.JTextField returnsField;
        private javax.swing.JLabel returnsLabel;
        private javax.swing.JLabel rpLabel1;
        private javax.swing.JLabel rpLabel2;
        private javax.swing.JLabel saveDraft;
        private javax.swing.JPanel shoppingReturns;
        private javax.swing.JPanel sumPanel;
        private javax.swing.JPanel tablePanel;
        private javax.swing.JTextField tfItem;
        private javax.swing.JLabel totalLabel;
        // End of variables declaration//GEN-END:variables
}
